// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package places

type Query struct {
}

type Sample struct {
	ID      *int    `json:"id,omitempty"`
	Title   *string `json:"title,omitempty"`
	TitleAr *string `json:"title_ar,omitempty"`
}
