// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: address.sql

package db

import (
	"context"
	"time"
)

const createLocation = `-- name: CreateLocation :one
INSERT INTO locations (
    lat,
    lng,
    created_at,
    updated_at )
    VALUES ( $1, $2, $3, $4 ) RETURNING id, lat, lng, created_at, updated_at
`

type CreateLocationParams struct {
	Lat       string    `json:"lat"`
	Lng       string    `json:"lng"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error) {
	row := q.db.QueryRow(ctx, createLocation,
		arg.Lat,
		arg.Lng,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.Lat,
		&i.Lng,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
