// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	CheckUsernameAndEmail(ctx context.Context, arg CheckUsernameAndEmailParams) (CheckUsernameAndEmailRow, error)
	CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error)
	CreatePlace(ctx context.Context, arg CreatePlaceParams) (int64, error)
	CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error)
	CreateRestaurant(ctx context.Context, name string) (Restaurant, error)
	CreateRestaurantBranch(ctx context.Context, arg CreateRestaurantBranchParams) (RestaurantBranch, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetAllUsers(ctx context.Context) ([]User, error)
	GetPlace(ctx context.Context, id int64) (Place, error)
	GetPlaces(ctx context.Context) ([]Place, error)
	GetRestaurant(ctx context.Context, id int64) (Restaurant, error)
	GetRestaurantBranch(ctx context.Context, id int64) (RestaurantBranch, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByName(ctx context.Context, username string) (User, error)
	GetUserStatus(ctx context.Context, id int64) (int64, error)
	ListRestaurantBranches(ctx context.Context, arg ListRestaurantBranchesParams) ([]RestaurantBranch, error)
	ListRestaurants(ctx context.Context, arg ListRestaurantsParams) ([]Restaurant, error)
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (User, error)
}

var _ Querier = (*Queries)(nil)
