// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
)

type Querier interface {
	CheckUsernameAndEmail(ctx context.Context, arg CheckUsernameAndEmailParams) (CheckUsernameAndEmailRow, error)
	CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error)
	CreatePlace(ctx context.Context, arg CreatePlaceParams) (int64, error)
	CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetPlace(ctx context.Context, id int64) (Place, error)
	GetPlaces(ctx context.Context) ([]Place, error)
	GetUserByName(ctx context.Context, username string) (User, error)
}

var _ Querier = (*Queries)(nil)
